version: '2'
services:
  php:
    build:
      context: .
      dockerfile: dockerfiles/php 
    ports:
     - "80:80"
    volumes:
    - ./src:/var/www/html/
    links:
      - db
  db:
    image: "mysql:5"
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root 
